@isTest
public class FormPrintPageController_Test {
    
    @isTest static void test(){
        FormPrintPageController a = new FormPrintPageController();
    }
    
        /*
         AccountCreateController.isFirstRun= false;
        Account acc1 = TestDataFactory.createTestAccountQuotePrint();
        String acc = acc1.id;
        String pageSize ='2';
        String pageNumber ='1';
        List<disco__form__c> frm = FormPrintPageController.fetch(acc);
        List<disco__form__c> getfrm = TestDataFactory.createTestFormPrint(acc1);
        List<disco__form__c> getform = FormPrintPageController.getForms(pageSize, pageNumber, acc);
        System.debug('Getform: ' +getfrm);
        Account accountId =  FormPrintPageController.nameReturn(acc);
        FormPrintPageController.CallFlow(acc);
        List<disco__form__c> Printfrm = FormPrintPageController.printForm(getfrm);
         
         }*/
}