global class InputDelete {//implements overcast.ScheduledCalloutHandler.DynamicCodeExecutor {//Commented by Sourav for Overcast uninstall
    //Overcast scheduler
    /*global void run(overcast__ScheduleTask__c task, overcast.ScheduledCalloutHandler.DynamicCodeHelper helper){
        database.executebatch(new InputDeleteBatch('sapCustomerDetail_ZBAPIECCCUSTOVERCAST__c'));
        database.executebatch(new InputDeleteBatch('sapCustomerDetail_GT_CUST_ADDRDATA__c'));
        database.executebatch(new InputDeleteBatch('sapCustomerDetail_RETURN__c'));
        database.executebatch(new InputDeleteBatch('sapCustomerDetail_GT_CUST_PF__c'));
        database.executebatch(new InputDeleteBatch('sapCustomerDetail_GT_CUST_SALESAREA__c'));
        database.executebatch(new InputDeleteBatch('sapCustomerDetail_GT_CUST_TC__c'));
        database.executebatch(new InputDeleteBatch('SAPC4CAssets_SaFoRePr__c'));
    }*///Commented by Sourav for Overcast uninstall
}